# Travis configuration file
# Read more under http://docs.travis-ci.com/user/build-configuration/

# Set the build language to Python
language: python
python:
  - "3.6"
install:
  - sudo apt-get install pandoc # pandoc for jupyter notebooks
  - sudo apt install graphviz # graphviz for class inheritance diagrams in docs
  - pip install tox-travis
script:
  - tox
after_success:
  - bash <(curl -s https://codecov.io/bash) # upload test coverage to codecov