# For more information about this pyproject.toml file, see
# PEP 518: https://www.python.org/dev/peps/pep-0518/


# Configuration of the black code style checker
# For more information about Black's usage of this file, see
# https://github.com/psf/black#pyprojecttoml
[tool.black]
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''


[tool.pylint.messages_control]
# From black: bad-continuation, bad-whitespace
# Exceptions we want to have: invalid-name
# Unclear to me: no-else-return, no-else-raise
disable = """
bad-continuation,
bad-whitespace,

invalid-name,

no-else-return,
no-else-raise,

fixme,
too-many-arguments,
missing-module-docstring,
abstract-method,
unused-argument,
too-many-branches,
arguments-differ,
redefined-builtin,
too-few-public-methods,
too-many-locals,
missing-function-docstring,
wrong-import-order,
no-self-use,
too-many-lines,
unused-variable,
broad-except,
abstract-class-instantiated,
protected-access,
duplicate-code,

too-many-instance-attributes,
too-many-statements,
attribute-defined-outside-init,
"""

[tool.pylint.format]
max-line-length = "88"

[tool.pylint.master]
extension-pkg-whitelist = "numpy"
