name: Linting

on: [push, pull_request]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install tox
        run: pip install tox
      - name: Run black through tox
        run: tox -e black
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install tox
        run: pip install tox
      - name: Run pylint through tox
        run: tox -e pylint
